#!/usr/bin/env bash
set -Eeuo pipefail
export LC_ALL=C
umask 077

VERSION="1.0.0"
CONF="/etc/nginx/conf.d/tps-tv-web.conf"
CERT="/etc/letsencrypt/live/studiosatweb-completo/fullchain.pem"
KEY="/etc/letsencrypt/live/studiosatweb-completo/privkey.pem"
PORTAL_ROOT="/var/www/portais"
PLAYER_ROOT="/var/www/emissoras"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="/var/backups/studiosat/tv-vhosts-fix-${STAMP}"
TMP="$(mktemp /tmp/tps-tv-web.conf.XXXXXX)"
APPLIED=0
HAD_OLD=0

RADIOS=(radioprincipal radiopop radiorock radioclassicas radiocountry)
TV_HOSTS=(
  tvkids.studiosatweb.com.br
  tvkidsweb.studiosatweb.com.br
  tvteens.studiosatweb.com.br
  tvviva.studiosatweb.com.br
  tvmaisjovem.studiosatweb.com.br
  www.tvkids.studiosatweb.com.br
  www.tvkidsweb.studiosatweb.com.br
  www.tvteens.studiosatweb.com.br
  www.tvviva.studiosatweb.com.br
  www.tvmaisjovem.studiosatweb.com.br
)

log(){ printf '[%s] %s\n' "$(date -Is)" "$*"; }
fail(){ printf 'FAIL: %s\n' "$*" >&2; return 1; }

radio_health(){
  local ch state code
  for ch in "${RADIOS[@]}"; do
    state="$(systemctl is-active "tps-${ch}-playout.service" 2>/dev/null || true)"
    [[ "$state" == "active" ]] || fail "tps-${ch}-playout.service=$state" || return 1
    code="$(curl -sS -L --max-time 6 -o /dev/null -w '%{http_code}' "http://127.0.0.1:8888/${ch}/index.m3u8" 2>/dev/null || true)"
    [[ "$code" == "200" ]] || fail "${ch} HLS=HTTP ${code}" || return 1
    printf 'RADIO %-18s service=%-8s HLS=%s\n' "$ch" "$state" "$code"
  done
}

rollback(){
  local rc="${1:-1}"
  trap - ERR INT TERM
  if [[ "$APPLIED" == "1" ]]; then
    log "ROLLBACK NGINX TV ONLY"
    if [[ "$HAD_OLD" == "1" ]]; then
      cp -a "$BACKUP/tps-tv-web.conf" "$CONF"
    else
      rm -f "$CONF"
    fi
    nginx -t >/dev/null 2>&1 || true
    systemctl reload nginx >/dev/null 2>&1 || true
    radio_health || true
  fi
  rm -f "$TMP"
  echo "AUTO_ROLLBACK_DONE=1"
  exit "$rc"
}

trap 'rollback $?' ERR INT TERM

[[ "$EUID" -eq 0 ]] || fail "execute como root"
for x in nginx systemctl curl grep awk sed sha256sum mktemp cp mv rm mkdir; do
  command -v "$x" >/dev/null 2>&1 || fail "dependência ausente: $x"
done
[[ -f "$CERT" ]] || fail "certificado ausente: $CERT"
[[ -f "$KEY" ]] || fail "chave TLS ausente: $KEY"

log "PRECHECK rádios"
radio_health
nginx -t >/dev/null

for f in \
  "$PLAYER_ROOT/tvkids.html" \
  "$PLAYER_ROOT/tvteens.html" \
  "$PLAYER_ROOT/tvviva.html" \
  "$PLAYER_ROOT/tvmaisjovem.html" \
  "$PORTAL_ROOT/www.tvkids.studiosatweb.com.br/index.html" \
  "$PORTAL_ROOT/www.tvkidsweb.studiosatweb.com.br/index.html" \
  "$PORTAL_ROOT/www.tvteens.studiosatweb.com.br/index.html" \
  "$PORTAL_ROOT/www.tvviva.studiosatweb.com.br/index.html" \
  "$PORTAL_ROOT/www.tvmaisjovem.studiosatweb.com.br/index.html"
do
  [[ -s "$f" ]] || fail "arquivo TV ausente/vazio: $f"
done

grep -qi 'tvkids' "$PLAYER_ROOT/tvkids.html" || fail "tvkids.html não parece TVKids"
grep -qi 'tvteens' "$PLAYER_ROOT/tvteens.html" || fail "tvteens.html não parece TVTeens"
grep -qi 'tvviva' "$PLAYER_ROOT/tvviva.html" || fail "tvviva.html não parece TVViva"
grep -qi 'tvmaisjovem' "$PLAYER_ROOT/tvmaisjovem.html" || fail "tvmaisjovem.html não parece TVMaisJovem"

mkdir -p "$BACKUP"
nginx -T > "$BACKUP/nginx-T.before.txt" 2>&1
if [[ -f "$CONF" ]]; then
  cp -a "$CONF" "$BACKUP/tps-tv-web.conf"
  HAD_OLD=1
fi
sha256sum "$PLAYER_ROOT"/tvkids.html "$PLAYER_ROOT"/tvteens.html "$PLAYER_ROOT"/tvviva.html "$PLAYER_ROOT"/tvmaisjovem.html > "$BACKUP/tv-player-sha256.txt"
find "$PORTAL_ROOT" -maxdepth 2 -type f -path '*/www.tv*.studiosatweb.com.br/index.html' -exec sha256sum {} \; | sort > "$BACKUP/tv-portal-sha256.txt"

ACTIVE_OWNERS="$BACKUP/tv-host-owners.before.txt"
nginx -T 2>&1 | grep -nE 'server_name[^;]*(tvkids|tvteens|tvviva|tvmaisjovem)' > "$ACTIVE_OWNERS" || true
if [[ -s "$ACTIVE_OWNERS" ]]; then
  echo "OWNERS_ATUAIS:" >&2
  cat "$ACTIVE_OWNERS" >&2
  fail "há server_name TV ativo; não vou criar vhost duplicado"
fi

cat > "$TMP" <<'NGINX'
# TPS StudioSat Web - TV endpoints only
# Generated by tps-fix-tv-vhosts-v1.0.sh

server {
    listen 80;
    listen [::]:80;
    server_name tvkids.studiosatweb.com.br tvkidsweb.studiosatweb.com.br tvteens.studiosatweb.com.br tvviva.studiosatweb.com.br tvmaisjovem.studiosatweb.com.br;
    return 301 https://$host$uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name tvkids.studiosatweb.com.br tvkidsweb.studiosatweb.com.br tvteens.studiosatweb.com.br tvviva.studiosatweb.com.br tvmaisjovem.studiosatweb.com.br;

    ssl_certificate /etc/letsencrypt/live/studiosatweb-completo/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studiosatweb-completo/privkey.pem;

    root /var/www/emissoras;
    if ($arg_station != "") { return 302 https://$host$uri; }

    location = / {
        set $page "tvkids.html";
        if ($host ~* "tvteens") { set $page "tvteens.html"; }
        if ($host ~* "tvviva") { set $page "tvviva.html"; }
        if ($host ~* "tvmaisjovem") { set $page "tvmaisjovem.html"; }
        try_files /$page =404;
    }

    location ~ ^/(tvkids|tvteens|tvviva|tvmaisjovem)/ {
        proxy_pass http://127.0.0.1:8888;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_buffering off;
        add_header Access-Control-Allow-Origin * always;
        add_header Cache-Control "no-cache" always;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name www.tvkids.studiosatweb.com.br www.tvkidsweb.studiosatweb.com.br www.tvteens.studiosatweb.com.br www.tvviva.studiosatweb.com.br www.tvmaisjovem.studiosatweb.com.br;
    return 301 https://$host$uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.tvkids.studiosatweb.com.br www.tvkidsweb.studiosatweb.com.br www.tvteens.studiosatweb.com.br www.tvviva.studiosatweb.com.br www.tvmaisjovem.studiosatweb.com.br;

    ssl_certificate /etc/letsencrypt/live/studiosatweb-completo/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studiosatweb-completo/privkey.pem;

    root /var/www/portais;
    if ($arg_station != "") { return 302 https://$host$uri; }

    location / {
        try_files /$host/index.html /$host/ =404;
    }

    location ~ ^/(tvkids|tvteens|tvviva|tvmaisjovem)/ {
        proxy_pass http://127.0.0.1:8888;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_buffering off;
        add_header Access-Control-Allow-Origin * always;
    }
}
NGINX

log "APLICANDO vhost TV isolado"
cp -a "$TMP" "$CONF.new"
chown root:root "$CONF.new"
chmod 0644 "$CONF.new"
mv -f "$CONF.new" "$CONF"
APPLIED=1

nginx -t
systemctl reload nginx
sleep 2

log "VALIDANDO rádios após reload gracioso"
radio_health

log "VALIDANDO 10 hosts TV localmente via SNI"
for host in "${TV_HOSTS[@]}"; do
  code="$(curl -k -sS --resolve "${host}:443:127.0.0.1" --max-time 8 -o /dev/null -w '%{http_code}' "https://${host}/" || true)"
  [[ "$code" == "200" ]] || fail "${host} HTTP=${code}"
  printf 'TV %-45s HTTP=%s\n' "$host" "$code"
done

log "VALIDANDO remoção de ?station=radioprincipal"
for host in www.tvkidsweb.studiosatweb.com.br tvkidsweb.studiosatweb.com.br; do
  headers="$(curl -k -sS --resolve "${host}:443:127.0.0.1" -D - -o /dev/null --max-time 8 "https://${host}/?station=radioprincipal")"
  code="$(awk 'toupper($1) ~ /^HTTP\// {c=$2} END{print c}' <<<"$headers")"
  location="$(awk 'BEGIN{IGNORECASE=1} /^Location:/ {sub(/\r$/,""); print $2}' <<<"$headers" | tail -n1)"
  [[ "$code" == "302" ]] || fail "${host} não removeu station (HTTP=$code)"
  [[ "$location" == "https://${host}/" ]] || fail "${host} Location inesperado: $location"
  printf 'CLEAN %-42s %s -> %s\n' "$host" "$code" "$location"
done

body="$(curl -k -sS --resolve 'www.tvkidsweb.studiosatweb.com.br:443:127.0.0.1' --max-time 8 'https://www.tvkidsweb.studiosatweb.com.br/')"
if grep -q 'history.replaceState(null.*station=' <<<"$body"; then
  fail "TVKidsWeb ainda está recebendo o radio player"
fi

echo "TVKIDSWEB_NOT_RADIO_PLAYER=PASS"
echo "NGINX_TV_VHOSTS=PASS"
echo "RADIOS_UNINTERRUPTED=PASS"
echo "BACKUP=$BACKUP"

trap - ERR INT TERM
rm -f "$TMP"
